/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;
import javax.swing.*;
import java.awt.event.*;
import java.util.Arrays;
import java.lang.reflect.Method;
/**
 *
 * @author Familiar
 */
public class CharacterCreator extends javax.swing.JPanel {
    String Per1_Nom;
    String Per3_Nom;
    String Class1;
    String Class3;
    
    /**
     * Creates new form CharacterCreator
     */
    public CharacterCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        Class1_P1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Per_Nom1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        Class1_P2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        Per_Nom3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Jugador 1");

        Class1_P1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caballero", "Guerrero Azteca", "Hada", "Mago", "Nigromante", "Reptiliano", "Troll", "Caballero oscuro", "Samurai" }));
        Class1_P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Class1_P1ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Clase:");

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jLabel12.setForeground(new java.awt.Color(30, 30, 30));
        jLabel12.setText("Nombre:");

        Per_Nom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Per_Nom1ActionPerformed(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Personaje 1");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(2, 2, 2)
                                .addComponent(Class1_P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Per_Nom1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel15)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Class1_P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(Per_Nom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Jugador 2");

        Class1_P2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caballero", "Guerrero Azteca", "Hada", "Mago", "Nigromante", "Reptiliano", "Troll", "Caballero oscuro", "Samurai" }));
        Class1_P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Class1_P2ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Clase:");

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jLabel21.setForeground(new java.awt.Color(30, 30, 30));
        jLabel21.setText("Nombre:");

        Per_Nom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Per_Nom3ActionPerformed(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Personaje 2");

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(2, 2, 2)
                                        .addComponent(Class1_P2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Per_Nom3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel23))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel20))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Class1_P2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(Per_Nom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Class1_P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Class1_P1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Class1_P1ActionPerformed

    private void Per_Nom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Per_Nom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Per_Nom1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Per1_Nom = Per_Nom1.getText();
        Per3_Nom = Per_Nom3.getText();
        Class1 = Class1_P1.getSelectedItem().toString();
        Class3 = Class1_P2.getSelectedItem().toString();
        //Creador de caballeros
        if (Class1 == "Caballero");{
            Clases.Caballero Kingth1 = new Clases.Caballero(15, Per1_Nom, 80, 100, 1);
            Menu.Knight.add(Kingth1);
        }
        
        if (Class3 == "Caballero");{
            Clases.Caballero Kingth3 = new Clases.Caballero(15, Per3_Nom, 80, 100, 3);
            Menu.Knight.add(Kingth3);
        }
        
        //Creador Aztecas
        if (Class1 == "Guerrero Azteca");{
            Clases.Guerrero_Azteca Aztec1 = new Clases.Guerrero_Azteca(20,Per1_Nom, 40, 100, 1);
            Menu.Aztec.add(Aztec1);
        }
        if (Class3 == "Guerrero Azteca");{
            Clases.Guerrero_Azteca Aztec3 = new Clases.Guerrero_Azteca(20, Per3_Nom, 40, 100, 3);
            Menu.Aztec.add(Aztec3);
        }
        
        //Creador Hada
        if (Class1 == "Hada");{
            Clases.Hada Fairy1 = new Clases.Hada(25,Per1_Nom, 20, 150, 1);
            Menu.Fairy.add(Fairy1);
        }
        if (Class3 == "Hada");{
            Clases.Hada Fairy3 = new Clases.Hada(25, Per3_Nom, 20, 150, 3);
            Menu.Fairy.add(Fairy3);
        }
        
        //Creador Magos
        if (Class1 == "Mago");{
            Clases.Mago Wizard1 = new Clases.Mago(20,Per1_Nom, 60, 110, 1);
            Menu.Wizard.add(Wizard1);
        }
        if (Class3 == "Mago");{
            Clases.Mago Wizard3 = new Clases.Mago(20, Per3_Nom, 60, 110, 3);
            Menu.Wizard.add(Wizard3);
        }
        
        //Creador Nigros
        if (Class1 == "Nigromante");{
            Clases.Nigromante Nigro1 = new Clases.Nigromante(21,Per1_Nom, 60, 110, 1);
            Menu.Nigro.add(Nigro1);
        }

        if (Class3 == "Nigromante");{
            Clases.Nigromante Nigro3 = new Clases.Nigromante(21, Per3_Nom, 60, 110, 3);
            Menu.Nigro.add(Nigro3);
        }

        
        //Creador Reptis
        if (Class1 == "Reptiliano");{
            Clases.Reptiliano Repti1 = new Clases.Reptiliano(16,Per1_Nom, 70, 100, 1);
            Menu.Reptil.add(Repti1);
        }

        if (Class3 == "Reptiliano");{
            Clases.Reptiliano Repti3 = new Clases.Reptiliano(16, Per3_Nom, 70, 100, 3);
            Menu.Reptil.add(Repti3);
        }

        
        //Creador Trolls
        if (Class1 == "Troll");{
            Clases.Troll troll1 = new Clases.Troll(10,Per1_Nom, 50, 200, 1);
            Menu.Troll.add(troll1);
        }

        if (Class3 == "Troll");{
            Clases.Troll troll3 = new Clases.Troll(10, Per3_Nom, 50, 200, 3);
            Menu.Troll.add(troll3);
        }

        
        //Creador Blacks
        if (Class1 == "Caballero oscuro");{
            Clases.caballero_oscuro black1 = new Clases.caballero_oscuro(20,Per1_Nom, 80, 70, 1);
            Menu.BlackK.add(black1);
        }
        if (Class3 == "Caballero oscuro");{
            Clases.caballero_oscuro black3 = new Clases.caballero_oscuro(20, Per3_Nom, 80, 70, 3);
            Menu.BlackK.add(black3);
        }

        
        //Creador samurais
        if (Class1 == "Samurai");{
            Clases.samurai sam1 = new Clases.samurai(20,Per1_Nom, 60, 100, 1);
            Menu.Sam.add(sam1);
        }
        if (Class3 == "Samurai");{
            Clases.samurai sam3 = new Clases.samurai(20, Per3_Nom, 60, 100, 3);
            Menu.Sam.add(sam3);
        }

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Class1_P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Class1_P2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Class1_P2ActionPerformed

    private void Per_Nom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Per_Nom3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Per_Nom3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Class1_P1;
    private javax.swing.JComboBox<String> Class1_P2;
    private javax.swing.JTextField Per_Nom1;
    private javax.swing.JTextField Per_Nom3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
